#!/bin/bash

# generate_table.sh 
# generate_table.sh depends on generate_table.awk. It will
# generate a file called `out.html`. It relies on the `headers` file generated by
# `get_table_headers.sh`. The `out.html` file will be the desired output, with
# the ics file converted into a table format that can be opened by opening the
# `out.html` file in Google Chrome or Mozilla Firefox.

path=$(dirname $0)

result=""
result+="<html><head><style>table, th, td { border: 1px solid black; }</style></head><body><table><tr>"

# Toss in all of the table headers
while read line; do
    result+="<th>$line</th>"
done < headers
table+="</tr>"

# Add in all of the table rows and table data
result+=$(cat $1 | $path/generate_table.awk)

# Close the table, then output it to out.html
result+="</table></table>"
echo $result > out.html
